jobs:
  include:
    - name: cu8
      env:
        - CUDA=8.0.61-1
        - CUDA_SHORT=8.0
        - UBUNTU_VERSION=ubuntu1604
        - BUILD_TAG=-cuda8.0
      dist: xenial
      compiler: gcc
      language: python
    - name: cu9
      env:
        - CUDA=9.2.148-1
        - CUDA_SHORT=9.2
        - UBUNTU_VERSION=ubuntu1604
        - BUILD_TAG=-cuda9.2
      dist: xenial
      language: python
    - name: cu10
      env:
        - CUDA=10.1.105-1
        - CUDA_SHORT=10.1
        - UBUNTU_VERSION=ubuntu1804
        - BUILD_TAG=-cuda10.1
      dist: bionic
      language: python
    - name: win
      os: windows
      language: cpp
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
        - PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - BUILD_TAG=-cuda10.1
script:
  - ./scripts/build_test.sh
before_deploy:
  - ./scripts/install_cuda.sh
deploy:
  provider: releases
  api_key: ${GITHUB_API_TOKEN}
  file: "dist/*"
  file_glob: true
  skip_cleanup: true
